version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sakila'
      MYSQL_ROOT_PASSWORD: 'admin'
    expose:
      - '3306'
    volumes:
      - ./db/backup:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql

  apache:
    restart: always
    expose:
      - '80'
    volumes:
      - ./apache/sites:/var/www/html
      - ./apache/config:/etc/apache2/sites-available
      - ./apache/logs:/var/log/apache2
    build:
      context: ./apache
      dockerfile: dockerfile
    depends_on:
      - db
  
  node:
    image: bonumlusor/kaiena
    restart: always
    expose:
      - '3000'
    volumes:
      - ./node:/var/www/html
    build: ./node

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /root/letsencrypt/certs:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf