version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'sakila'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./db/backup:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
  web:
    build:
      context: ./web
      dockerfile: dockerfile
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db